name: Reusable workflow example

on:
  pull_request:
    branches: [ main ]
    types: [ opened, edited, reopened, synchronize ]

jobs:
  call-remote-workflow:
    uses: Gerardo0579/A_Maze_Ing/.github/workflows/e2e-test.yml@workflow_test
    with:
      config-path: "Test input value 1"
      